// dx-frontend/frameworks/storybook/code/renderers/preact/template/components/Pre.jsx
/* eslint-disable react/react-in-jsx-scope */
// eslint-disable-next-line import/no-extraneous-dependencies
import PropTypes from 'prop-types';

export const Pre = ({ style, object, text }) => (
  <pre style={style} data-testid="pre">
    {object ? JSON.stringify(object, null, 2) : text}
  </pre>
);

Pre.propTypes = {
  style: PropTypes.shape({}),
  object: PropTypes.shape({}),
  text: PropTypes.string,
};

Pre.defaultProps = {
  style: {},
  object: null,
  text: '',
};

// dx-frontend/frameworks/storybook/code/renderers/vue/template/components/Pre.vue
<template>
  <pre data-testid="pre" :style="style">{{ finalText }}</pre>
</template>

<script>
export default {
  name: 'my-pre',

  props: {
    // deepscan-disable-next-line
    style: {
      type: Object,
    },
    object: {
      type: Object,
    },
    text: {
      type: String,
      default: '',
    },
  },

  computed: {
    finalText() {
      return this.object ? JSON.stringify(this.object, null, 2) : this.text;
    },
  },
};
</script>
