// dx-frontend/frameworks/storybook/code/renderers/svelte/template/components/Pre.svelte
<script>
  /**
   * Styles to use for this component
   */
  export let style = {};
  /**
   * Object to log
   */
  export let object;
  /**
   * Text content to log
   */
  export let text = '';

  const finalText = object ? JSON.stringify(object, null, 2) : text;
</script>

<pre data-testid="pre" {style}>{finalText}</pre>

// dx-frontend/frameworks/storybook/code/renderers/vue/template/components/Pre.vue
<template>
  <pre data-testid="pre" :style="style">{{ finalText }}</pre>
</template>

<script>
export default {
  name: 'my-pre',

  props: {
    // deepscan-disable-next-line
    style: {
      type: Object,
    },
    object: {
      type: Object,
    },
    text: {
      type: String,
      default: '',
    },
  },

  computed: {
    finalText() {
      return this.object ? JSON.stringify(this.object, null, 2) : this.text;
    },
  },
};
</script>
