// dx-frontend/frameworks/storybook/code/renderers/vue3/template/components/Form.vue
<template>
  <form id="interaction-test-form" @submit.prevent="onSubmit">
    <label>
      Enter Value
      <input type="text" data-testid="value" v-model="value" required />
    </label>
    <button type="submit">Submit</button>
    <p v-if="complete">Completed!!</p>
  </form>
</template>

<script>
export default {
  name: 'my-form',

  props: {
    onSuccess: {
      type: Function,
    },
  },

  data() {
    return {
      value: '',
      complete: false,
    };
  },

  methods: {
    onSubmit() {
      this.onSuccess(this.value);
      setTimeout(() => {
        this.complete = true;
      }, 500);
      setTimeout(() => {
        this.complete = false;
      }, 1500);
    },
  },
};
</script>

// dx-frontend/frameworks/storybook/code/renderers/svelte/template/components/Form.svelte
<script>
  /**
   * Callback for when the form succeeds
   */
  export let onSuccess;

  let value = '';
  function handleClick(event) {
    value = event.target.value;
  }

  let complete = false;
  function handleSubmit() {
    onSuccess(value);

    setTimeout(() => {
      complete = true;
    }, 500);

    setTimeout(() => {
      complete = false;
    }, 1500);
  }
</script>

<form id="interaction-test-form" on:submit|preventDefault={handleSubmit}>
  <label>
    Enter Value
    <input type="text" data-testid="value" bind:value required on:click={handleClick} />
  </label>
  <button type="submit">Submit</button>
  {#if complete}<p>Completed!!</p>{/if}
</form>
