// dx-frontend/frameworks/storybook/code/renderers/svelte/template/components/Form.svelte
<script>
  /**
   * Callback for when the form succeeds
   */
  export let onSuccess;

  let value = '';
  function handleClick(event) {
    value = event.target.value;
  }

  let complete = false;
  function handleSubmit() {
    onSuccess(value);

    setTimeout(() => {
      complete = true;
    }, 500);

    setTimeout(() => {
      complete = false;
    }, 1500);
  }
</script>

<form id="interaction-test-form" on:submit|preventDefault={handleSubmit}>
  <label>
    Enter Value
    <input type="text" data-testid="value" bind:value required on:click={handleClick} />
  </label>
  <button type="submit">Submit</button>
  {#if complete}<p>Completed!!</p>{/if}
</form>

// dx-frontend/frameworks/storybook/code/frameworks/angular/template/components/form.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'storybook-form',
  template: `
    <form id="interaction-test-form" (submit)="handleSubmit($event)">
      <label>
        Enter Value
        <input type="text" data-testid="value" [(ngModel)]="value" required />
      </label>
      <button type="submit">Submit</button>
      <p *ngIf="complete">Completed!!</p>
    </form>
  `,
})
export default class FormComponent {
  /**
   * Optional success handler
   */
  @Output()
  onSuccess = new EventEmitter<string>();

  value = '';

  complete = false;

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    this.onSuccess.emit(this.value);
    setTimeout(() => {
      this.complete = true;
    }, 500);
    setTimeout(() => {
      this.complete = false;
    }, 1500);
  }
}
