// dx-frontend/frameworks/storybook/code/renderers/svelte/template/components/Pre.svelte
<script>
  /**
   * Styles to use for this component
   */
  export let style = {};
  /**
   * Object to log
   */
  export let object;
  /**
   * Text content to log
   */
  export let text = '';

  const finalText = object ? JSON.stringify(object, null, 2) : text;
</script>

<pre data-testid="pre" {style}>{finalText}</pre>

// dx-frontend/frameworks/storybook/code/frameworks/angular/template/components/pre.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'storybook-pre',
  template: `<pre data-testid="pre" [ngStyle]="style">{{ finalText }}</pre>`,
})
export default class PreComponent {
  /**
   * Styles to apply to the component
   */
  @Input()
  style?: Object;

  /**
   * An object to render
   */
  @Input()
  object?: Object;

  /**
   * The code to render
   */
  @Input()
  text?: string;

  get finalText() {
    return this.object ? JSON.stringify(this.object, null, 2) : this.text;
  }
}
